# Generated by Django 5.2.4 on 2025-07-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_a', models.FloatField()),
                ('product_b', models.FloatField()),
                ('objective_value', models.FloatField()),
                ('machine_1_lhs', models.FloatField()),
                ('machine_1_rhs', models.FloatField()),
                ('machine_2_lhs', models.FloatField()),
                ('machine_2_rhs', models.FloatField()),
                ('status', models.CharField(max_length=10)),
                ('termination', models.CharField(max_length=10)),
                ('solve_time', models.FloatField()),
                ('error_rc', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
